/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as ReportNumbersIndexImport } from './routes/report-numbers/index'
import { Route as DashboardIndexImport } from './routes/dashboard/index'
import { Route as ReportNumbersCreateImport } from './routes/report-numbers/create'
import { Route as DashboardFraudNumbersIndexImport } from './routes/dashboard/fraud-numbers/index'
import { Route as DashboardCaseFilesIndexImport } from './routes/dashboard/case-files/index'
import { Route as DashboardFraudNumbersCreateImport } from './routes/dashboard/fraud-numbers/create'
import { Route as DashboardCaseFilesCreateImport } from './routes/dashboard/case-files/create'

// Create/Update Routes

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ReportNumbersIndexRoute = ReportNumbersIndexImport.update({
  id: '/report-numbers/',
  path: '/report-numbers/',
  getParentRoute: () => rootRoute,
} as any)

const DashboardIndexRoute = DashboardIndexImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRoute,
} as any)

const ReportNumbersCreateRoute = ReportNumbersCreateImport.update({
  id: '/report-numbers/create',
  path: '/report-numbers/create',
  getParentRoute: () => rootRoute,
} as any)

const DashboardFraudNumbersIndexRoute = DashboardFraudNumbersIndexImport.update(
  {
    id: '/dashboard/fraud-numbers/',
    path: '/dashboard/fraud-numbers/',
    getParentRoute: () => rootRoute,
  } as any,
)

const DashboardCaseFilesIndexRoute = DashboardCaseFilesIndexImport.update({
  id: '/dashboard/case-files/',
  path: '/dashboard/case-files/',
  getParentRoute: () => rootRoute,
} as any)

const DashboardFraudNumbersCreateRoute =
  DashboardFraudNumbersCreateImport.update({
    id: '/dashboard/fraud-numbers/create',
    path: '/dashboard/fraud-numbers/create',
    getParentRoute: () => rootRoute,
  } as any)

const DashboardCaseFilesCreateRoute = DashboardCaseFilesCreateImport.update({
  id: '/dashboard/case-files/create',
  path: '/dashboard/case-files/create',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/report-numbers/create': {
      id: '/report-numbers/create'
      path: '/report-numbers/create'
      fullPath: '/report-numbers/create'
      preLoaderRoute: typeof ReportNumbersCreateImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardIndexImport
      parentRoute: typeof rootRoute
    }
    '/report-numbers/': {
      id: '/report-numbers/'
      path: '/report-numbers'
      fullPath: '/report-numbers'
      preLoaderRoute: typeof ReportNumbersIndexImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/case-files/create': {
      id: '/dashboard/case-files/create'
      path: '/dashboard/case-files/create'
      fullPath: '/dashboard/case-files/create'
      preLoaderRoute: typeof DashboardCaseFilesCreateImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/fraud-numbers/create': {
      id: '/dashboard/fraud-numbers/create'
      path: '/dashboard/fraud-numbers/create'
      fullPath: '/dashboard/fraud-numbers/create'
      preLoaderRoute: typeof DashboardFraudNumbersCreateImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/case-files/': {
      id: '/dashboard/case-files/'
      path: '/dashboard/case-files'
      fullPath: '/dashboard/case-files'
      preLoaderRoute: typeof DashboardCaseFilesIndexImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/fraud-numbers/': {
      id: '/dashboard/fraud-numbers/'
      path: '/dashboard/fraud-numbers'
      fullPath: '/dashboard/fraud-numbers'
      preLoaderRoute: typeof DashboardFraudNumbersIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/report-numbers/create': typeof ReportNumbersCreateRoute
  '/dashboard': typeof DashboardIndexRoute
  '/report-numbers': typeof ReportNumbersIndexRoute
  '/dashboard/case-files/create': typeof DashboardCaseFilesCreateRoute
  '/dashboard/fraud-numbers/create': typeof DashboardFraudNumbersCreateRoute
  '/dashboard/case-files': typeof DashboardCaseFilesIndexRoute
  '/dashboard/fraud-numbers': typeof DashboardFraudNumbersIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/report-numbers/create': typeof ReportNumbersCreateRoute
  '/dashboard': typeof DashboardIndexRoute
  '/report-numbers': typeof ReportNumbersIndexRoute
  '/dashboard/case-files/create': typeof DashboardCaseFilesCreateRoute
  '/dashboard/fraud-numbers/create': typeof DashboardFraudNumbersCreateRoute
  '/dashboard/case-files': typeof DashboardCaseFilesIndexRoute
  '/dashboard/fraud-numbers': typeof DashboardFraudNumbersIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/report-numbers/create': typeof ReportNumbersCreateRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/report-numbers/': typeof ReportNumbersIndexRoute
  '/dashboard/case-files/create': typeof DashboardCaseFilesCreateRoute
  '/dashboard/fraud-numbers/create': typeof DashboardFraudNumbersCreateRoute
  '/dashboard/case-files/': typeof DashboardCaseFilesIndexRoute
  '/dashboard/fraud-numbers/': typeof DashboardFraudNumbersIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/report-numbers/create'
    | '/dashboard'
    | '/report-numbers'
    | '/dashboard/case-files/create'
    | '/dashboard/fraud-numbers/create'
    | '/dashboard/case-files'
    | '/dashboard/fraud-numbers'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/report-numbers/create'
    | '/dashboard'
    | '/report-numbers'
    | '/dashboard/case-files/create'
    | '/dashboard/fraud-numbers/create'
    | '/dashboard/case-files'
    | '/dashboard/fraud-numbers'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/report-numbers/create'
    | '/dashboard/'
    | '/report-numbers/'
    | '/dashboard/case-files/create'
    | '/dashboard/fraud-numbers/create'
    | '/dashboard/case-files/'
    | '/dashboard/fraud-numbers/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ReportNumbersCreateRoute: typeof ReportNumbersCreateRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  ReportNumbersIndexRoute: typeof ReportNumbersIndexRoute
  DashboardCaseFilesCreateRoute: typeof DashboardCaseFilesCreateRoute
  DashboardFraudNumbersCreateRoute: typeof DashboardFraudNumbersCreateRoute
  DashboardCaseFilesIndexRoute: typeof DashboardCaseFilesIndexRoute
  DashboardFraudNumbersIndexRoute: typeof DashboardFraudNumbersIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ReportNumbersCreateRoute: ReportNumbersCreateRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  ReportNumbersIndexRoute: ReportNumbersIndexRoute,
  DashboardCaseFilesCreateRoute: DashboardCaseFilesCreateRoute,
  DashboardFraudNumbersCreateRoute: DashboardFraudNumbersCreateRoute,
  DashboardCaseFilesIndexRoute: DashboardCaseFilesIndexRoute,
  DashboardFraudNumbersIndexRoute: DashboardFraudNumbersIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/report-numbers/create",
        "/dashboard/",
        "/report-numbers/",
        "/dashboard/case-files/create",
        "/dashboard/fraud-numbers/create",
        "/dashboard/case-files/",
        "/dashboard/fraud-numbers/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/report-numbers/create": {
      "filePath": "report-numbers/create.tsx"
    },
    "/dashboard/": {
      "filePath": "dashboard/index.tsx"
    },
    "/report-numbers/": {
      "filePath": "report-numbers/index.tsx"
    },
    "/dashboard/case-files/create": {
      "filePath": "dashboard/case-files/create.tsx"
    },
    "/dashboard/fraud-numbers/create": {
      "filePath": "dashboard/fraud-numbers/create.tsx"
    },
    "/dashboard/case-files/": {
      "filePath": "dashboard/case-files/index.tsx"
    },
    "/dashboard/fraud-numbers/": {
      "filePath": "dashboard/fraud-numbers/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
