/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ForbiddenImport } from './routes/forbidden'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as UsersIndexImport } from './routes/users/index'
import { Route as UserRoleIndexImport } from './routes/user-role/index'
import { Route as DashboardIndexImport } from './routes/dashboard/index'
import { Route as AccountsIndexImport } from './routes/accounts/index'
import { Route as UsersCreateImport } from './routes/users/create'
import { Route as UserRoleCreateImport } from './routes/user-role/create'
import { Route as DashboardReportNumbersIndexImport } from './routes/dashboard/report-numbers/index'
import { Route as DashboardFraudNumbersIndexImport } from './routes/dashboard/fraud-numbers/index'
import { Route as DashboardCaseFilesIndexImport } from './routes/dashboard/case-files/index'
import { Route as UsersEditUserIdImport } from './routes/users/edit/$userId'
import { Route as DashboardReportNumbersCreateImport } from './routes/dashboard/report-numbers/create'
import { Route as DashboardFraudNumbersCreateImport } from './routes/dashboard/fraud-numbers/create'
import { Route as DashboardCaseFilesCreateImport } from './routes/dashboard/case-files/create'
import { Route as DashboardCaseFilesCaseIdImport } from './routes/dashboard/case-files/$caseId'

// Create/Update Routes

const ForbiddenRoute = ForbiddenImport.update({
  id: '/forbidden',
  path: '/forbidden',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const UsersIndexRoute = UsersIndexImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => rootRoute,
} as any)

const UserRoleIndexRoute = UserRoleIndexImport.update({
  id: '/user-role/',
  path: '/user-role/',
  getParentRoute: () => rootRoute,
} as any)

const DashboardIndexRoute = DashboardIndexImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRoute,
} as any)

const AccountsIndexRoute = AccountsIndexImport.update({
  id: '/accounts/',
  path: '/accounts/',
  getParentRoute: () => rootRoute,
} as any)

const UsersCreateRoute = UsersCreateImport.update({
  id: '/users/create',
  path: '/users/create',
  getParentRoute: () => rootRoute,
} as any)

const UserRoleCreateRoute = UserRoleCreateImport.update({
  id: '/user-role/create',
  path: '/user-role/create',
  getParentRoute: () => rootRoute,
} as any)

const DashboardReportNumbersIndexRoute =
  DashboardReportNumbersIndexImport.update({
    id: '/dashboard/report-numbers/',
    path: '/dashboard/report-numbers/',
    getParentRoute: () => rootRoute,
  } as any)

const DashboardFraudNumbersIndexRoute = DashboardFraudNumbersIndexImport.update(
  {
    id: '/dashboard/fraud-numbers/',
    path: '/dashboard/fraud-numbers/',
    getParentRoute: () => rootRoute,
  } as any,
)

const DashboardCaseFilesIndexRoute = DashboardCaseFilesIndexImport.update({
  id: '/dashboard/case-files/',
  path: '/dashboard/case-files/',
  getParentRoute: () => rootRoute,
} as any)

const UsersEditUserIdRoute = UsersEditUserIdImport.update({
  id: '/users/edit/$userId',
  path: '/users/edit/$userId',
  getParentRoute: () => rootRoute,
} as any)

const DashboardReportNumbersCreateRoute =
  DashboardReportNumbersCreateImport.update({
    id: '/dashboard/report-numbers/create',
    path: '/dashboard/report-numbers/create',
    getParentRoute: () => rootRoute,
  } as any)

const DashboardFraudNumbersCreateRoute =
  DashboardFraudNumbersCreateImport.update({
    id: '/dashboard/fraud-numbers/create',
    path: '/dashboard/fraud-numbers/create',
    getParentRoute: () => rootRoute,
  } as any)

const DashboardCaseFilesCreateRoute = DashboardCaseFilesCreateImport.update({
  id: '/dashboard/case-files/create',
  path: '/dashboard/case-files/create',
  getParentRoute: () => rootRoute,
} as any)

const DashboardCaseFilesCaseIdRoute = DashboardCaseFilesCaseIdImport.update({
  id: '/dashboard/case-files/$caseId',
  path: '/dashboard/case-files/$caseId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/forbidden': {
      id: '/forbidden'
      path: '/forbidden'
      fullPath: '/forbidden'
      preLoaderRoute: typeof ForbiddenImport
      parentRoute: typeof rootRoute
    }
    '/user-role/create': {
      id: '/user-role/create'
      path: '/user-role/create'
      fullPath: '/user-role/create'
      preLoaderRoute: typeof UserRoleCreateImport
      parentRoute: typeof rootRoute
    }
    '/users/create': {
      id: '/users/create'
      path: '/users/create'
      fullPath: '/users/create'
      preLoaderRoute: typeof UsersCreateImport
      parentRoute: typeof rootRoute
    }
    '/accounts/': {
      id: '/accounts/'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsIndexImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardIndexImport
      parentRoute: typeof rootRoute
    }
    '/user-role/': {
      id: '/user-role/'
      path: '/user-role'
      fullPath: '/user-role'
      preLoaderRoute: typeof UserRoleIndexImport
      parentRoute: typeof rootRoute
    }
    '/users/': {
      id: '/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersIndexImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/case-files/$caseId': {
      id: '/dashboard/case-files/$caseId'
      path: '/dashboard/case-files/$caseId'
      fullPath: '/dashboard/case-files/$caseId'
      preLoaderRoute: typeof DashboardCaseFilesCaseIdImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/case-files/create': {
      id: '/dashboard/case-files/create'
      path: '/dashboard/case-files/create'
      fullPath: '/dashboard/case-files/create'
      preLoaderRoute: typeof DashboardCaseFilesCreateImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/fraud-numbers/create': {
      id: '/dashboard/fraud-numbers/create'
      path: '/dashboard/fraud-numbers/create'
      fullPath: '/dashboard/fraud-numbers/create'
      preLoaderRoute: typeof DashboardFraudNumbersCreateImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/report-numbers/create': {
      id: '/dashboard/report-numbers/create'
      path: '/dashboard/report-numbers/create'
      fullPath: '/dashboard/report-numbers/create'
      preLoaderRoute: typeof DashboardReportNumbersCreateImport
      parentRoute: typeof rootRoute
    }
    '/users/edit/$userId': {
      id: '/users/edit/$userId'
      path: '/users/edit/$userId'
      fullPath: '/users/edit/$userId'
      preLoaderRoute: typeof UsersEditUserIdImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/case-files/': {
      id: '/dashboard/case-files/'
      path: '/dashboard/case-files'
      fullPath: '/dashboard/case-files'
      preLoaderRoute: typeof DashboardCaseFilesIndexImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/fraud-numbers/': {
      id: '/dashboard/fraud-numbers/'
      path: '/dashboard/fraud-numbers'
      fullPath: '/dashboard/fraud-numbers'
      preLoaderRoute: typeof DashboardFraudNumbersIndexImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/report-numbers/': {
      id: '/dashboard/report-numbers/'
      path: '/dashboard/report-numbers'
      fullPath: '/dashboard/report-numbers'
      preLoaderRoute: typeof DashboardReportNumbersIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/forbidden': typeof ForbiddenRoute
  '/user-role/create': typeof UserRoleCreateRoute
  '/users/create': typeof UsersCreateRoute
  '/accounts': typeof AccountsIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/user-role': typeof UserRoleIndexRoute
  '/users': typeof UsersIndexRoute
  '/dashboard/case-files/$caseId': typeof DashboardCaseFilesCaseIdRoute
  '/dashboard/case-files/create': typeof DashboardCaseFilesCreateRoute
  '/dashboard/fraud-numbers/create': typeof DashboardFraudNumbersCreateRoute
  '/dashboard/report-numbers/create': typeof DashboardReportNumbersCreateRoute
  '/users/edit/$userId': typeof UsersEditUserIdRoute
  '/dashboard/case-files': typeof DashboardCaseFilesIndexRoute
  '/dashboard/fraud-numbers': typeof DashboardFraudNumbersIndexRoute
  '/dashboard/report-numbers': typeof DashboardReportNumbersIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/forbidden': typeof ForbiddenRoute
  '/user-role/create': typeof UserRoleCreateRoute
  '/users/create': typeof UsersCreateRoute
  '/accounts': typeof AccountsIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/user-role': typeof UserRoleIndexRoute
  '/users': typeof UsersIndexRoute
  '/dashboard/case-files/$caseId': typeof DashboardCaseFilesCaseIdRoute
  '/dashboard/case-files/create': typeof DashboardCaseFilesCreateRoute
  '/dashboard/fraud-numbers/create': typeof DashboardFraudNumbersCreateRoute
  '/dashboard/report-numbers/create': typeof DashboardReportNumbersCreateRoute
  '/users/edit/$userId': typeof UsersEditUserIdRoute
  '/dashboard/case-files': typeof DashboardCaseFilesIndexRoute
  '/dashboard/fraud-numbers': typeof DashboardFraudNumbersIndexRoute
  '/dashboard/report-numbers': typeof DashboardReportNumbersIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/forbidden': typeof ForbiddenRoute
  '/user-role/create': typeof UserRoleCreateRoute
  '/users/create': typeof UsersCreateRoute
  '/accounts/': typeof AccountsIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/user-role/': typeof UserRoleIndexRoute
  '/users/': typeof UsersIndexRoute
  '/dashboard/case-files/$caseId': typeof DashboardCaseFilesCaseIdRoute
  '/dashboard/case-files/create': typeof DashboardCaseFilesCreateRoute
  '/dashboard/fraud-numbers/create': typeof DashboardFraudNumbersCreateRoute
  '/dashboard/report-numbers/create': typeof DashboardReportNumbersCreateRoute
  '/users/edit/$userId': typeof UsersEditUserIdRoute
  '/dashboard/case-files/': typeof DashboardCaseFilesIndexRoute
  '/dashboard/fraud-numbers/': typeof DashboardFraudNumbersIndexRoute
  '/dashboard/report-numbers/': typeof DashboardReportNumbersIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/forbidden'
    | '/user-role/create'
    | '/users/create'
    | '/accounts'
    | '/dashboard'
    | '/user-role'
    | '/users'
    | '/dashboard/case-files/$caseId'
    | '/dashboard/case-files/create'
    | '/dashboard/fraud-numbers/create'
    | '/dashboard/report-numbers/create'
    | '/users/edit/$userId'
    | '/dashboard/case-files'
    | '/dashboard/fraud-numbers'
    | '/dashboard/report-numbers'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/forbidden'
    | '/user-role/create'
    | '/users/create'
    | '/accounts'
    | '/dashboard'
    | '/user-role'
    | '/users'
    | '/dashboard/case-files/$caseId'
    | '/dashboard/case-files/create'
    | '/dashboard/fraud-numbers/create'
    | '/dashboard/report-numbers/create'
    | '/users/edit/$userId'
    | '/dashboard/case-files'
    | '/dashboard/fraud-numbers'
    | '/dashboard/report-numbers'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/forbidden'
    | '/user-role/create'
    | '/users/create'
    | '/accounts/'
    | '/dashboard/'
    | '/user-role/'
    | '/users/'
    | '/dashboard/case-files/$caseId'
    | '/dashboard/case-files/create'
    | '/dashboard/fraud-numbers/create'
    | '/dashboard/report-numbers/create'
    | '/users/edit/$userId'
    | '/dashboard/case-files/'
    | '/dashboard/fraud-numbers/'
    | '/dashboard/report-numbers/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ForbiddenRoute: typeof ForbiddenRoute
  UserRoleCreateRoute: typeof UserRoleCreateRoute
  UsersCreateRoute: typeof UsersCreateRoute
  AccountsIndexRoute: typeof AccountsIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  UserRoleIndexRoute: typeof UserRoleIndexRoute
  UsersIndexRoute: typeof UsersIndexRoute
  DashboardCaseFilesCaseIdRoute: typeof DashboardCaseFilesCaseIdRoute
  DashboardCaseFilesCreateRoute: typeof DashboardCaseFilesCreateRoute
  DashboardFraudNumbersCreateRoute: typeof DashboardFraudNumbersCreateRoute
  DashboardReportNumbersCreateRoute: typeof DashboardReportNumbersCreateRoute
  UsersEditUserIdRoute: typeof UsersEditUserIdRoute
  DashboardCaseFilesIndexRoute: typeof DashboardCaseFilesIndexRoute
  DashboardFraudNumbersIndexRoute: typeof DashboardFraudNumbersIndexRoute
  DashboardReportNumbersIndexRoute: typeof DashboardReportNumbersIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ForbiddenRoute: ForbiddenRoute,
  UserRoleCreateRoute: UserRoleCreateRoute,
  UsersCreateRoute: UsersCreateRoute,
  AccountsIndexRoute: AccountsIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  UserRoleIndexRoute: UserRoleIndexRoute,
  UsersIndexRoute: UsersIndexRoute,
  DashboardCaseFilesCaseIdRoute: DashboardCaseFilesCaseIdRoute,
  DashboardCaseFilesCreateRoute: DashboardCaseFilesCreateRoute,
  DashboardFraudNumbersCreateRoute: DashboardFraudNumbersCreateRoute,
  DashboardReportNumbersCreateRoute: DashboardReportNumbersCreateRoute,
  UsersEditUserIdRoute: UsersEditUserIdRoute,
  DashboardCaseFilesIndexRoute: DashboardCaseFilesIndexRoute,
  DashboardFraudNumbersIndexRoute: DashboardFraudNumbersIndexRoute,
  DashboardReportNumbersIndexRoute: DashboardReportNumbersIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/forbidden",
        "/user-role/create",
        "/users/create",
        "/accounts/",
        "/dashboard/",
        "/user-role/",
        "/users/",
        "/dashboard/case-files/$caseId",
        "/dashboard/case-files/create",
        "/dashboard/fraud-numbers/create",
        "/dashboard/report-numbers/create",
        "/users/edit/$userId",
        "/dashboard/case-files/",
        "/dashboard/fraud-numbers/",
        "/dashboard/report-numbers/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/forbidden": {
      "filePath": "forbidden.tsx"
    },
    "/user-role/create": {
      "filePath": "user-role/create.tsx"
    },
    "/users/create": {
      "filePath": "users/create.tsx"
    },
    "/accounts/": {
      "filePath": "accounts/index.tsx"
    },
    "/dashboard/": {
      "filePath": "dashboard/index.tsx"
    },
    "/user-role/": {
      "filePath": "user-role/index.tsx"
    },
    "/users/": {
      "filePath": "users/index.tsx"
    },
    "/dashboard/case-files/$caseId": {
      "filePath": "dashboard/case-files/$caseId.tsx"
    },
    "/dashboard/case-files/create": {
      "filePath": "dashboard/case-files/create.tsx"
    },
    "/dashboard/fraud-numbers/create": {
      "filePath": "dashboard/fraud-numbers/create.tsx"
    },
    "/dashboard/report-numbers/create": {
      "filePath": "dashboard/report-numbers/create.tsx"
    },
    "/users/edit/$userId": {
      "filePath": "users/edit/$userId.tsx"
    },
    "/dashboard/case-files/": {
      "filePath": "dashboard/case-files/index.tsx"
    },
    "/dashboard/fraud-numbers/": {
      "filePath": "dashboard/fraud-numbers/index.tsx"
    },
    "/dashboard/report-numbers/": {
      "filePath": "dashboard/report-numbers/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
